version: '3'

services:
  pgdb:
    build:
      context: .
      dockerfile: db_dockerfile
    container_name: pgdb
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend_dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py loaddata data.json &&
      python3 manage.py runserver 0.0.0.0:8000"

    depends_on:
      - pgdb

  frontend:
    build:
      context: .
      dockerfile: frontend_dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    
    depends_on:
      - backend
